name: CI Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./main-interface
        run: npm ci

      - name: Run Tests
        working-directory: ./main-interface
        run: npm test
        env:
          HOST: localhost
          SESSION_SECRET: da_secret
          STUDENT_ADMIN_PATH: 8150
          TUTOR_ADMIN_PATH: 8010
