name: CI Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./main-interface
        run: npm ci

      - name: Run Tests
        working-directory: ./main-interface
        run: npm test
        env:
          HOST: localhost
          MAIN_PORT: 8090
          REDIS_SESSION_HOST: localhost
          REDIS_SESSION_PORT: 8099
          SESSION_SECRET: da_secret
          MYSQL_TUTOR_PORT: 8022
          MYSQL_TUTOR_USERNAME: user
          MYSQL_TUTOR_PASSWORD: password
          MYSQL_TUTOR_DB: tutors
          MYSQL_STUDENT_PORT: 3306
          MYSQL_STUDENT_USERNAME: user
          MYSQL_STUDENT_PASSWORD: password
          MYSQL_STUDENT_DB: students
          STUDENT_ADMIN_PATH: 8150
          TUTOR_ADMIN_PATH: 8010
