name: CI Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        run: redis-server

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./main-interface
        run: npm ci

      - name: Run Tests
        working-directory: ./main-interface
        run: npm test
        env:
          HOST: localhost
          MAIN_PORT: 8090
          REDIS_SESSION_PORT: 6379
          SESSION_SECRET: da_secret
          STUDENT_ADMIN_PATH: 8150
          TUTOR_ADMIN_PATH: 8010
