name: Docker

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Get Git Tag
        run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}:1" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./main-interface
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/edufi-main-interface:${{ env.GIT_TAG }}
